declare module 'winapi-bindings' {
  export function RegGetValue(hkey: string, subKey: string, valueName: string): { value: any } | null;
  export function ShellExecuteEx(params: any): any;
  export function GetVolumeInformation(rootPath: string): any;
  export function GetDiskFreeSpaceEx(path: string): any;
  export function GetFileAttributes(path: string): any;
  export function SetFileAttributes(path: string, attributes: number): any;
  export function CreateHardLink(fileName: string, existingFileName: string): boolean;
  export function CreateSymbolicLink(symlinkFileName: string, targetFileName: string, flags: number): boolean;
  export function GetLastError(): number;
  export function FormatMessage(flags: number, source: any, messageId: number, languageId: number, buffer: any, size: number, args: any): number;
  export function CloseHandle(handle: any): boolean;
  export function FindFirstFile(fileName: string, findFileData: any): any;
  export function FindNextFile(findHandle: any, findFileData: any): boolean;
  export function FindClose(findHandle: any): boolean;
  export function GetFileInformationByHandle(fileHandle: any, fileInformation: any): boolean;
  export function CreateFile(fileName: string, desiredAccess: number, shareMode: number, securityAttributes: any, creationDisposition: number, flagsAndAttributes: number, templateFile: any): any;
  export function DeviceIoControl(device: any, ioControlCode: number, inBuffer: any, inBufferSize: number, outBuffer: any, outBufferSize: number, bytesReturned: any, overlapped: any): boolean;
  export function GetLogicalDrives(): number;
  export function GetDriveType(rootPathName: string): number;
  export function QueryDosDevice(deviceName: string, targetPath: any, maxTargetPath: number): number;
  export function DefineDosDevice(flags: number, deviceName: string, targetPath: string): boolean;
  export function GetCurrentProcess(): any;
  export function OpenProcessToken(processHandle: any, desiredAccess: number, tokenHandle: any): boolean;
  export function GetTokenInformation(tokenHandle: any, tokenInformationClass: number, tokenInformation: any, tokenInformationLength: number, returnLength: any): boolean;
  export function LookupPrivilegeValue(systemName: string, name: string, luid: any): boolean;
  export function AdjustTokenPrivileges(tokenHandle: any, disableAllPrivileges: boolean, newState: any, bufferLength: number, previousState: any, returnLength: any): boolean;
  export function IsUserAnAdmin(): boolean;
  export function GetUserName(): string;
  export function GetComputerName(): string;
  export function GetSystemDirectory(): string;
  export function GetWindowsDirectory(): string;
  export function GetTempPath(): string;
  export function ExpandEnvironmentStrings(src: string): string;
  export function GetEnvironmentVariable(name: string): string;
  export function SetEnvironmentVariable(name: string, value: string): boolean;
  export function GetCurrentDirectory(): string;
  export function SetCurrentDirectory(pathName: string): boolean;
  export function GetFullPathName(fileName: string): string;
  export function GetShortPathName(longPath: string): string;
  export function GetLongPathName(shortPath: string): string;
  export function PathIsDirectory(path: string): boolean;
  export function PathFileExists(path: string): boolean;
  export function PathIsRelative(path: string): boolean;
  export function PathCanonicalize(dst: string, src: string): boolean;
  export function PathCombine(dst: string, dir: string, file: string): string;
  export function PathCommonPrefix(file1: string, file2: string, commonPath: string): number;
  export function PathCompactPath(hdc: any, path: string, dx: number): boolean;
  export function PathCompactPathEx(out: string, src: string, maxChars: number, flags: number): boolean;
  export function PathCreateFromUrl(url: string, path: string, pathLength: any, flags: number): number;
  export function PathFindExtension(path: string): string;
  export function PathFindFileName(path: string): string;
  export function PathFindNextComponent(path: string): string;
  export function PathGetArgs(path: string): string;
  export function PathGetCharType(ch: string): number;
  export function PathGetDriveNumber(path: string): number;
  export function PathIsContentType(path: string, contentType: string): boolean;
  export function PathIsFileSpec(path: string): boolean;
  export function PathIsPrefix(prefix: string, path: string): boolean;
  export function PathIsRoot(path: string): boolean;
  export function PathIsSameRoot(path1: string, path2: string): boolean;
  export function PathIsSystemFolder(path: string, attributes: number): boolean;
  export function PathIsUNC(path: string): boolean;
  export function PathIsUNCServer(path: string): boolean;
  export function PathIsUNCServerShare(path: string): boolean;
  export function PathIsURL(path: string): boolean;
  export function PathMakePretty(path: string): boolean;
  export function PathMatchSpec(path: string, spec: string): boolean;
  export function PathParseIconLocation(iconPath: string): number;
  export function PathQuoteSpaces(path: string): void;
  export function PathRelativePathTo(path: string, from: string, fromAttributes: number, to: string, toAttributes: number): boolean;
  export function PathRemoveArgs(path: string): void;
  export function PathRemoveBackslash(path: string): string;
  export function PathRemoveBlanks(path: string): void;
  export function PathRemoveExtension(path: string): void;
  export function PathRemoveFileSpec(path: string): boolean;
  export function PathRenameExtension(path: string, ext: string): boolean;
  export function PathSearchAndQualify(path: string, fullPath: string, fullPathLength: number): boolean;
  export function PathSetDlgItemPath(hDlg: any, id: number, path: string): void;
  export function PathSkipRoot(path: string): string;
  export function PathStripPath(path: string): void;
  export function PathStripToRoot(path: string): boolean;
  export function PathUnExpandEnvStrings(path: string, buf: string, bufSize: number): boolean;
  export function PathUnmakeSystemFolder(path: string): boolean;
  export function PathUnquoteSpaces(path: string): void;
  export function UrlApplyScheme(url: string, scheme: string, flags: number): string;
  export function UrlCanonicalize(url: string, flags: number): string;
  export function UrlCombine(base: string, relative: string, flags: number): string;
  export function UrlCompare(url1: string, url2: string, ignoreSlash: boolean): number;
  export function UrlCreateFromPath(path: string): string;
  export function UrlEscape(url: string, flags: number): string;
  export function UrlGetLocation(url: string): string;
  export function UrlGetPart(url: string, part: number, flags: number): string;
  export function UrlHash(url: string, flags: number): number;
  export function UrlIs(url: string, urlIs: number): boolean;
  export function UrlIsFileUrl(url: string): boolean;
  export function UrlIsNoHistory(url: string): boolean;
  export function UrlIsOpaque(url: string): boolean;
  export function UrlUnescape(url: string, flags: number): string;
  
  // Default export for compatibility
  const winapi: any;
  export default winapi;
}