"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = InfoComponent;
const React = __importStar(require("react"));
const BS = __importStar(require("react-bootstrap"));
const common_1 = require("../common");
const vortex_api_1 = require("vortex-api");
const react_i18next_1 = require("react-i18next");
function InfoComponent(props) {
    const { onToggleModsState } = props;
    const t = (0, react_i18next_1.useTranslation)(common_1.I18N_NAMESPACE).t;
    const toggleModsState = React.useCallback((enable) => {
        onToggleModsState(enable);
    }, [onToggleModsState]);
    return (React.createElement("div", { style: { display: 'flex', flexDirection: 'column', gap: '12px', marginRight: '16px' } },
        React.createElement("div", null,
            React.createElement("p", null,
                t('You can adjust the load order for The Witcher 3 by dragging and dropping '
                    + 'mods up or down on this page.  If you are using several mods that add scripts you may need to use '
                    + 'the Witcher 3 Script merger. For more information see: ', { ns: common_1.I18N_NAMESPACE }),
                React.createElement("a", { onClick: () => vortex_api_1.util.opn('https://wiki.nexusmods.com/index.php/Modding_The_Witcher_3_with_Vortex') }, t('Modding The Witcher 3 with Vortex.', { ns: common_1.I18N_NAMESPACE })))),
        React.createElement("div", { style: { height: '80%' } },
            React.createElement("p", null, t('Please note:', { ns: common_1.I18N_NAMESPACE })),
            React.createElement("ul", null,
                React.createElement("li", null, t('For Witcher 3, the mod with the lowest index number (by default, the mod sorted at the top) overrides mods with a higher index number.', { ns: common_1.I18N_NAMESPACE })),
                React.createElement("li", null, t('If you cannot see your mod in this load order, you may need to add it manually (see our wiki for details).', { ns: common_1.I18N_NAMESPACE })),
                React.createElement("li", null, t('When managing menu mods, mod settings changed inside the game will be detected by Vortex as external changes - that is expected, '
                    + 'choose to use the newer file and your settings will be made persistent.', { ns: common_1.I18N_NAMESPACE })),
                React.createElement("li", null, t('Merges generated by the Witcher 3 Script merger must be loaded first and are locked in the first load order slot.', { ns: common_1.I18N_NAMESPACE }))),
            React.createElement(BS.Button, { onClick: () => toggleModsState(false), style: { marginBottom: '5px', width: 'min-content' } }, t('Disable All')),
            React.createElement("br", null),
            React.createElement(BS.Button, { onClick: () => toggleModsState(true), style: { marginBottom: '5px', width: 'min-content' } }, t('Enable All ')))));
}
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiSW5mb0NvbXBvbmVudC5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIkluZm9Db21wb25lbnQudHN4Il0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0FBWUEsZ0NBNkNDO0FBeERELDZDQUErQjtBQUMvQixvREFBc0M7QUFDdEMsc0NBQTJDO0FBRTNDLDJDQUE4QztBQUM5QyxpREFBK0M7QUFNL0MsU0FBd0IsYUFBYSxDQUFDLEtBQXlCO0lBQzdELE1BQU0sRUFBRSxpQkFBaUIsRUFBRSxHQUFHLEtBQUssQ0FBQztJQUNwQyxNQUFNLENBQUMsR0FBRyxJQUFBLDhCQUFjLEVBQUMsdUJBQWMsQ0FBQyxDQUFDLENBQUMsQ0FBQztJQUMzQyxNQUFNLGVBQWUsR0FBRyxLQUFLLENBQUMsV0FBVyxDQUFDLENBQUMsTUFBTSxFQUFFLEVBQUU7UUFDbkQsaUJBQWlCLENBQUMsTUFBTSxDQUFDLENBQUM7SUFDNUIsQ0FBQyxFQUFFLENBQUMsaUJBQWlCLENBQUMsQ0FBQyxDQUFDO0lBRXhCLE9BQU8sQ0FDTCw2QkFBSyxLQUFLLEVBQUUsRUFBRSxPQUFPLEVBQUUsTUFBTSxFQUFFLGFBQWEsRUFBRSxRQUFRLEVBQUUsR0FBRyxFQUFFLE1BQU0sRUFBRSxXQUFXLEVBQUUsTUFBTSxFQUFFO1FBQ3RGO1lBQ0U7Z0JBQ0csQ0FBQyxDQUFDLDJFQUEyRTtzQkFDMUUsb0dBQW9HO3NCQUNwRyx5REFBeUQsRUFBRSxFQUFFLEVBQUUsRUFBRSx1QkFBYyxFQUFFLENBQUM7Z0JBQ3RGLDJCQUFHLE9BQU8sRUFBRSxHQUFHLEVBQUUsQ0FBQyxpQkFBSSxDQUFDLEdBQUcsQ0FBQyx3RUFBd0UsQ0FBQyxJQUNqRyxDQUFDLENBQUMsb0NBQW9DLEVBQUUsRUFBRSxFQUFFLEVBQUUsdUJBQWMsRUFBRSxDQUFDLENBQzlELENBQ0YsQ0FDQTtRQUNOLDZCQUFLLEtBQUssRUFBRSxFQUFFLE1BQU0sRUFBRSxLQUFLLEVBQUU7WUFDM0IsK0JBQUksQ0FBQyxDQUFDLGNBQWMsRUFBRSxFQUFFLEVBQUUsRUFBRSx1QkFBYyxFQUFFLENBQUMsQ0FBSztZQUNsRDtnQkFDRSxnQ0FBSyxDQUFDLENBQUMsd0lBQXdJLEVBQUUsRUFBRSxFQUFFLEVBQUUsdUJBQWMsRUFBRSxDQUFDLENBQU07Z0JBQzlLLGdDQUFLLENBQUMsQ0FBQyw0R0FBNEcsRUFBRSxFQUFFLEVBQUUsRUFBRSx1QkFBYyxFQUFFLENBQUMsQ0FBTTtnQkFDbEosZ0NBQUssQ0FBQyxDQUFDLG1JQUFtSTtzQkFDdEkseUVBQXlFLEVBQzNFLEVBQUUsRUFBRSxFQUFFLHVCQUFjLEVBQUUsQ0FBQyxDQUFNO2dCQUMvQixnQ0FBSyxDQUFDLENBQUMsbUhBQW1ILEVBQUUsRUFBRSxFQUFFLEVBQUUsdUJBQWMsRUFBRSxDQUFDLENBQU0sQ0FDdEo7WUFDTCxvQkFBQyxFQUFFLENBQUMsTUFBTSxJQUNSLE9BQU8sRUFBRSxHQUFHLEVBQUUsQ0FBQyxlQUFlLENBQUMsS0FBSyxDQUFDLEVBQ3JDLEtBQUssRUFBRSxFQUFFLFlBQVksRUFBRSxLQUFLLEVBQUUsS0FBSyxFQUFFLGFBQWEsRUFBRSxJQUVuRCxDQUFDLENBQUMsYUFBYSxDQUFDLENBQ1A7WUFDWiwrQkFBTTtZQUNOLG9CQUFDLEVBQUUsQ0FBQyxNQUFNLElBQ1IsT0FBTyxFQUFFLEdBQUcsRUFBRSxDQUFDLGVBQWUsQ0FBQyxJQUFJLENBQUMsRUFDcEMsS0FBSyxFQUFFLEVBQUUsWUFBWSxFQUFFLEtBQUssRUFBRSxLQUFLLEVBQUUsYUFBYSxFQUFFLElBRW5ELENBQUMsQ0FBQyxhQUFhLENBQUMsQ0FDUCxDQUNSLENBQ0YsQ0FDVCxDQUFDO0FBQ0osQ0FBQyIsInNvdXJjZXNDb250ZW50IjpbIi8qIGVzbGludC1kaXNhYmxlICovXG5pbXBvcnQgKiBhcyBSZWFjdCBmcm9tICdyZWFjdCc7XG5pbXBvcnQgKiBhcyBCUyBmcm9tICdyZWFjdC1ib290c3RyYXAnO1xuaW1wb3J0IHsgSTE4Tl9OQU1FU1BBQ0UgfSBmcm9tICcuLi9jb21tb24nO1xuXG5pbXBvcnQgeyBGbGV4TGF5b3V0LCB1dGlsIH0gZnJvbSAndm9ydGV4LWFwaSc7XG5pbXBvcnQgeyB1c2VUcmFuc2xhdGlvbiB9IGZyb20gJ3JlYWN0LWkxOG5leHQnO1xuXG5pbnRlcmZhY2UgSW5mb0NvbXBvbmVudFByb3BzIHtcbiAgb25Ub2dnbGVNb2RzU3RhdGU6IChlbmFibGU6IGJvb2xlYW4pID0+IHZvaWQ7XG59XG5cbmV4cG9ydCBkZWZhdWx0IGZ1bmN0aW9uIEluZm9Db21wb25lbnQocHJvcHM6IEluZm9Db21wb25lbnRQcm9wcykge1xuICBjb25zdCB7IG9uVG9nZ2xlTW9kc1N0YXRlIH0gPSBwcm9wcztcbiAgY29uc3QgdCA9IHVzZVRyYW5zbGF0aW9uKEkxOE5fTkFNRVNQQUNFKS50O1xuICBjb25zdCB0b2dnbGVNb2RzU3RhdGUgPSBSZWFjdC51c2VDYWxsYmFjaygoZW5hYmxlKSA9PiB7XG4gICAgb25Ub2dnbGVNb2RzU3RhdGUoZW5hYmxlKTtcbiAgfSwgW29uVG9nZ2xlTW9kc1N0YXRlXSk7XG5cbiAgcmV0dXJuIChcbiAgICA8ZGl2IHN0eWxlPXt7IGRpc3BsYXk6ICdmbGV4JywgZmxleERpcmVjdGlvbjogJ2NvbHVtbicsIGdhcDogJzEycHgnLCBtYXJnaW5SaWdodDogJzE2cHgnIH19PlxuICAgICAgICA8ZGl2PlxuICAgICAgICAgIDxwPlxuICAgICAgICAgICAge3QoJ1lvdSBjYW4gYWRqdXN0IHRoZSBsb2FkIG9yZGVyIGZvciBUaGUgV2l0Y2hlciAzIGJ5IGRyYWdnaW5nIGFuZCBkcm9wcGluZyAnXG4gICAgICAgICAgICAgICsgJ21vZHMgdXAgb3IgZG93biBvbiB0aGlzIHBhZ2UuICBJZiB5b3UgYXJlIHVzaW5nIHNldmVyYWwgbW9kcyB0aGF0IGFkZCBzY3JpcHRzIHlvdSBtYXkgbmVlZCB0byB1c2UgJ1xuICAgICAgICAgICAgICArICd0aGUgV2l0Y2hlciAzIFNjcmlwdCBtZXJnZXIuIEZvciBtb3JlIGluZm9ybWF0aW9uIHNlZTogJywgeyBuczogSTE4Tl9OQU1FU1BBQ0UgfSl9XG4gICAgICAgICAgICA8YSBvbkNsaWNrPXsoKSA9PiB1dGlsLm9wbignaHR0cHM6Ly93aWtpLm5leHVzbW9kcy5jb20vaW5kZXgucGhwL01vZGRpbmdfVGhlX1dpdGNoZXJfM193aXRoX1ZvcnRleCcpfT5cbiAgICAgICAgICAgICAge3QoJ01vZGRpbmcgVGhlIFdpdGNoZXIgMyB3aXRoIFZvcnRleC4nLCB7IG5zOiBJMThOX05BTUVTUEFDRSB9KX1cbiAgICAgICAgICAgIDwvYT5cbiAgICAgICAgICA8L3A+XG4gICAgICAgIDwvZGl2PlxuICAgICAgICA8ZGl2IHN0eWxlPXt7IGhlaWdodDogJzgwJScgfX0+XG4gICAgICAgICAgPHA+e3QoJ1BsZWFzZSBub3RlOicsIHsgbnM6IEkxOE5fTkFNRVNQQUNFIH0pfTwvcD5cbiAgICAgICAgICA8dWw+XG4gICAgICAgICAgICA8bGk+e3QoJ0ZvciBXaXRjaGVyIDMsIHRoZSBtb2Qgd2l0aCB0aGUgbG93ZXN0IGluZGV4IG51bWJlciAoYnkgZGVmYXVsdCwgdGhlIG1vZCBzb3J0ZWQgYXQgdGhlIHRvcCkgb3ZlcnJpZGVzIG1vZHMgd2l0aCBhIGhpZ2hlciBpbmRleCBudW1iZXIuJywgeyBuczogSTE4Tl9OQU1FU1BBQ0UgfSl9PC9saT5cbiAgICAgICAgICAgIDxsaT57dCgnSWYgeW91IGNhbm5vdCBzZWUgeW91ciBtb2QgaW4gdGhpcyBsb2FkIG9yZGVyLCB5b3UgbWF5IG5lZWQgdG8gYWRkIGl0IG1hbnVhbGx5IChzZWUgb3VyIHdpa2kgZm9yIGRldGFpbHMpLicsIHsgbnM6IEkxOE5fTkFNRVNQQUNFIH0pfTwvbGk+XG4gICAgICAgICAgICA8bGk+e3QoJ1doZW4gbWFuYWdpbmcgbWVudSBtb2RzLCBtb2Qgc2V0dGluZ3MgY2hhbmdlZCBpbnNpZGUgdGhlIGdhbWUgd2lsbCBiZSBkZXRlY3RlZCBieSBWb3J0ZXggYXMgZXh0ZXJuYWwgY2hhbmdlcyAtIHRoYXQgaXMgZXhwZWN0ZWQsICdcbiAgICAgICAgICAgICAgKyAnY2hvb3NlIHRvIHVzZSB0aGUgbmV3ZXIgZmlsZSBhbmQgeW91ciBzZXR0aW5ncyB3aWxsIGJlIG1hZGUgcGVyc2lzdGVudC4nLFxuICAgICAgICAgICAgICB7IG5zOiBJMThOX05BTUVTUEFDRSB9KX08L2xpPlxuICAgICAgICAgICAgPGxpPnt0KCdNZXJnZXMgZ2VuZXJhdGVkIGJ5IHRoZSBXaXRjaGVyIDMgU2NyaXB0IG1lcmdlciBtdXN0IGJlIGxvYWRlZCBmaXJzdCBhbmQgYXJlIGxvY2tlZCBpbiB0aGUgZmlyc3QgbG9hZCBvcmRlciBzbG90LicsIHsgbnM6IEkxOE5fTkFNRVNQQUNFIH0pfTwvbGk+XG4gICAgICAgICAgPC91bD5cbiAgICAgICAgICA8QlMuQnV0dG9uXG4gICAgICAgICAgICBvbkNsaWNrPXsoKSA9PiB0b2dnbGVNb2RzU3RhdGUoZmFsc2UpfVxuICAgICAgICAgICAgc3R5bGU9e3sgbWFyZ2luQm90dG9tOiAnNXB4Jywgd2lkdGg6ICdtaW4tY29udGVudCcgfX1cbiAgICAgICAgICA+XG4gICAgICAgICAgICB7dCgnRGlzYWJsZSBBbGwnKX1cbiAgICAgICAgICA8L0JTLkJ1dHRvbj5cbiAgICAgICAgICA8YnIgLz5cbiAgICAgICAgICA8QlMuQnV0dG9uXG4gICAgICAgICAgICBvbkNsaWNrPXsoKSA9PiB0b2dnbGVNb2RzU3RhdGUodHJ1ZSl9XG4gICAgICAgICAgICBzdHlsZT17eyBtYXJnaW5Cb3R0b206ICc1cHgnLCB3aWR0aDogJ21pbi1jb250ZW50JyB9fVxuICAgICAgICAgID5cbiAgICAgICAgICAgIHt0KCdFbmFibGUgQWxsICcpfVxuICAgICAgICAgIDwvQlMuQnV0dG9uPlxuICAgICAgICA8L2Rpdj5cbiAgICAgIDwvZGl2PlxuICApO1xufVxuIl19