"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
const React = __importStar(require("react"));
const BS = __importStar(require("react-bootstrap"));
const common_1 = require("../common");
const vortex_api_1 = require("vortex-api");
const react_i18next_1 = require("react-i18next");
function InfoComponent(props) {
    const { onToggleModsState } = props;
    const t = (0, react_i18next_1.useTranslation)(common_1.I18N_NAMESPACE).t;
    const toggleModsState = React.useCallback((enable) => {
        onToggleModsState(enable);
    }, [onToggleModsState]);
    return (React.createElement("div", { style: { display: 'flex', flexDirection: 'column', gap: '12px', marginRight: '16px' } },
        React.createElement("div", null,
            React.createElement("p", null,
                t('You can adjust the load order for The Witcher 3 by dragging and dropping '
                    + 'mods up or down on this page.  If you are using several mods that add scripts you may need to use '
                    + 'the Witcher 3 Script merger. For more information see: ', { ns: common_1.I18N_NAMESPACE }),
                React.createElement("a", { onClick: () => vortex_api_1.util.opn('https://wiki.nexusmods.com/index.php/Modding_The_Witcher_3_with_Vortex') }, t('Modding The Witcher 3 with Vortex.', { ns: common_1.I18N_NAMESPACE })))),
        React.createElement("div", { style: { height: '80%' } },
            React.createElement("p", null, t('Please note:', { ns: common_1.I18N_NAMESPACE })),
            React.createElement("ul", null,
                React.createElement("li", null, t('For Witcher 3, the mod with the lowest index number (by default, the mod sorted at the top) overrides mods with a higher index number.', { ns: common_1.I18N_NAMESPACE })),
                React.createElement("li", null, t('If you cannot see your mod in this load order, you may need to add it manually (see our wiki for details).', { ns: common_1.I18N_NAMESPACE })),
                React.createElement("li", null, t('When managing menu mods, mod settings changed inside the game will be detected by Vortex as external changes - that is expected, '
                    + 'choose to use the newer file and your settings will be made persistent.', { ns: common_1.I18N_NAMESPACE })),
                React.createElement("li", null, t('Merges generated by the Witcher 3 Script merger must be loaded first and are locked in the first load order slot.', { ns: common_1.I18N_NAMESPACE }))),
            React.createElement(BS.Button, { onClick: () => toggleModsState(false), style: { marginBottom: '5px', width: 'min-content' } }, t('Disable All')),
            React.createElement("br", null),
            React.createElement(BS.Button, { onClick: () => toggleModsState(true), style: { marginBottom: '5px', width: 'min-content' } }, t('Enable All ')))));
}
exports.default = InfoComponent;
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiSW5mb0NvbXBvbmVudC5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIkluZm9Db21wb25lbnQudHN4Il0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7QUFDQSw2Q0FBK0I7QUFDL0Isb0RBQXNDO0FBQ3RDLHNDQUEyQztBQUUzQywyQ0FBOEM7QUFDOUMsaURBQStDO0FBTS9DLFNBQXdCLGFBQWEsQ0FBQyxLQUF5QjtJQUM3RCxNQUFNLEVBQUUsaUJBQWlCLEVBQUUsR0FBRyxLQUFLLENBQUM7SUFDcEMsTUFBTSxDQUFDLEdBQUcsSUFBQSw4QkFBYyxFQUFDLHVCQUFjLENBQUMsQ0FBQyxDQUFDLENBQUM7SUFDM0MsTUFBTSxlQUFlLEdBQUcsS0FBSyxDQUFDLFdBQVcsQ0FBQyxDQUFDLE1BQU0sRUFBRSxFQUFFO1FBQ25ELGlCQUFpQixDQUFDLE1BQU0sQ0FBQyxDQUFDO0lBQzVCLENBQUMsRUFBRSxDQUFDLGlCQUFpQixDQUFDLENBQUMsQ0FBQztJQUV4QixPQUFPLENBQ0wsNkJBQUssS0FBSyxFQUFFLEVBQUUsT0FBTyxFQUFFLE1BQU0sRUFBRSxhQUFhLEVBQUUsUUFBUSxFQUFFLEdBQUcsRUFBRSxNQUFNLEVBQUUsV0FBVyxFQUFFLE1BQU0sRUFBRTtRQUN0RjtZQUNFO2dCQUNHLENBQUMsQ0FBQywyRUFBMkU7c0JBQzFFLG9HQUFvRztzQkFDcEcseURBQXlELEVBQUUsRUFBRSxFQUFFLEVBQUUsdUJBQWMsRUFBRSxDQUFDO2dCQUN0RiwyQkFBRyxPQUFPLEVBQUUsR0FBRyxFQUFFLENBQUMsaUJBQUksQ0FBQyxHQUFHLENBQUMsd0VBQXdFLENBQUMsSUFDakcsQ0FBQyxDQUFDLG9DQUFvQyxFQUFFLEVBQUUsRUFBRSxFQUFFLHVCQUFjLEVBQUUsQ0FBQyxDQUM5RCxDQUNGLENBQ0E7UUFDTiw2QkFBSyxLQUFLLEVBQUUsRUFBRSxNQUFNLEVBQUUsS0FBSyxFQUFFO1lBQzNCLCtCQUFJLENBQUMsQ0FBQyxjQUFjLEVBQUUsRUFBRSxFQUFFLEVBQUUsdUJBQWMsRUFBRSxDQUFDLENBQUs7WUFDbEQ7Z0JBQ0UsZ0NBQUssQ0FBQyxDQUFDLHdJQUF3SSxFQUFFLEVBQUUsRUFBRSxFQUFFLHVCQUFjLEVBQUUsQ0FBQyxDQUFNO2dCQUM5SyxnQ0FBSyxDQUFDLENBQUMsNEdBQTRHLEVBQUUsRUFBRSxFQUFFLEVBQUUsdUJBQWMsRUFBRSxDQUFDLENBQU07Z0JBQ2xKLGdDQUFLLENBQUMsQ0FBQyxtSUFBbUk7c0JBQ3RJLHlFQUF5RSxFQUMzRSxFQUFFLEVBQUUsRUFBRSx1QkFBYyxFQUFFLENBQUMsQ0FBTTtnQkFDL0IsZ0NBQUssQ0FBQyxDQUFDLG1IQUFtSCxFQUFFLEVBQUUsRUFBRSxFQUFFLHVCQUFjLEVBQUUsQ0FBQyxDQUFNLENBQ3RKO1lBQ0wsb0JBQUMsRUFBRSxDQUFDLE1BQU0sSUFDUixPQUFPLEVBQUUsR0FBRyxFQUFFLENBQUMsZUFBZSxDQUFDLEtBQUssQ0FBQyxFQUNyQyxLQUFLLEVBQUUsRUFBRSxZQUFZLEVBQUUsS0FBSyxFQUFFLEtBQUssRUFBRSxhQUFhLEVBQUUsSUFFbkQsQ0FBQyxDQUFDLGFBQWEsQ0FBQyxDQUNQO1lBQ1osK0JBQU07WUFDTixvQkFBQyxFQUFFLENBQUMsTUFBTSxJQUNSLE9BQU8sRUFBRSxHQUFHLEVBQUUsQ0FBQyxlQUFlLENBQUMsSUFBSSxDQUFDLEVBQ3BDLEtBQUssRUFBRSxFQUFFLFlBQVksRUFBRSxLQUFLLEVBQUUsS0FBSyxFQUFFLGFBQWEsRUFBRSxJQUVuRCxDQUFDLENBQUMsYUFBYSxDQUFDLENBQ1AsQ0FDUixDQUNGLENBQ1QsQ0FBQztBQUNKLENBQUM7QUE3Q0QsZ0NBNkNDIiwic291cmNlc0NvbnRlbnQiOlsiLyogZXNsaW50LWRpc2FibGUgKi9cbmltcG9ydCAqIGFzIFJlYWN0IGZyb20gJ3JlYWN0JztcbmltcG9ydCAqIGFzIEJTIGZyb20gJ3JlYWN0LWJvb3RzdHJhcCc7XG5pbXBvcnQgeyBJMThOX05BTUVTUEFDRSB9IGZyb20gJy4uL2NvbW1vbic7XG5cbmltcG9ydCB7IEZsZXhMYXlvdXQsIHV0aWwgfSBmcm9tICd2b3J0ZXgtYXBpJztcbmltcG9ydCB7IHVzZVRyYW5zbGF0aW9uIH0gZnJvbSAncmVhY3QtaTE4bmV4dCc7XG5cbmludGVyZmFjZSBJbmZvQ29tcG9uZW50UHJvcHMge1xuICBvblRvZ2dsZU1vZHNTdGF0ZTogKGVuYWJsZTogYm9vbGVhbikgPT4gdm9pZDtcbn1cblxuZXhwb3J0IGRlZmF1bHQgZnVuY3Rpb24gSW5mb0NvbXBvbmVudChwcm9wczogSW5mb0NvbXBvbmVudFByb3BzKSB7XG4gIGNvbnN0IHsgb25Ub2dnbGVNb2RzU3RhdGUgfSA9IHByb3BzO1xuICBjb25zdCB0ID0gdXNlVHJhbnNsYXRpb24oSTE4Tl9OQU1FU1BBQ0UpLnQ7XG4gIGNvbnN0IHRvZ2dsZU1vZHNTdGF0ZSA9IFJlYWN0LnVzZUNhbGxiYWNrKChlbmFibGUpID0+IHtcbiAgICBvblRvZ2dsZU1vZHNTdGF0ZShlbmFibGUpO1xuICB9LCBbb25Ub2dnbGVNb2RzU3RhdGVdKTtcblxuICByZXR1cm4gKFxuICAgIDxkaXYgc3R5bGU9e3sgZGlzcGxheTogJ2ZsZXgnLCBmbGV4RGlyZWN0aW9uOiAnY29sdW1uJywgZ2FwOiAnMTJweCcsIG1hcmdpblJpZ2h0OiAnMTZweCcgfX0+XG4gICAgICAgIDxkaXY+XG4gICAgICAgICAgPHA+XG4gICAgICAgICAgICB7dCgnWW91IGNhbiBhZGp1c3QgdGhlIGxvYWQgb3JkZXIgZm9yIFRoZSBXaXRjaGVyIDMgYnkgZHJhZ2dpbmcgYW5kIGRyb3BwaW5nICdcbiAgICAgICAgICAgICAgKyAnbW9kcyB1cCBvciBkb3duIG9uIHRoaXMgcGFnZS4gIElmIHlvdSBhcmUgdXNpbmcgc2V2ZXJhbCBtb2RzIHRoYXQgYWRkIHNjcmlwdHMgeW91IG1heSBuZWVkIHRvIHVzZSAnXG4gICAgICAgICAgICAgICsgJ3RoZSBXaXRjaGVyIDMgU2NyaXB0IG1lcmdlci4gRm9yIG1vcmUgaW5mb3JtYXRpb24gc2VlOiAnLCB7IG5zOiBJMThOX05BTUVTUEFDRSB9KX1cbiAgICAgICAgICAgIDxhIG9uQ2xpY2s9eygpID0+IHV0aWwub3BuKCdodHRwczovL3dpa2kubmV4dXNtb2RzLmNvbS9pbmRleC5waHAvTW9kZGluZ19UaGVfV2l0Y2hlcl8zX3dpdGhfVm9ydGV4Jyl9PlxuICAgICAgICAgICAgICB7dCgnTW9kZGluZyBUaGUgV2l0Y2hlciAzIHdpdGggVm9ydGV4LicsIHsgbnM6IEkxOE5fTkFNRVNQQUNFIH0pfVxuICAgICAgICAgICAgPC9hPlxuICAgICAgICAgIDwvcD5cbiAgICAgICAgPC9kaXY+XG4gICAgICAgIDxkaXYgc3R5bGU9e3sgaGVpZ2h0OiAnODAlJyB9fT5cbiAgICAgICAgICA8cD57dCgnUGxlYXNlIG5vdGU6JywgeyBuczogSTE4Tl9OQU1FU1BBQ0UgfSl9PC9wPlxuICAgICAgICAgIDx1bD5cbiAgICAgICAgICAgIDxsaT57dCgnRm9yIFdpdGNoZXIgMywgdGhlIG1vZCB3aXRoIHRoZSBsb3dlc3QgaW5kZXggbnVtYmVyIChieSBkZWZhdWx0LCB0aGUgbW9kIHNvcnRlZCBhdCB0aGUgdG9wKSBvdmVycmlkZXMgbW9kcyB3aXRoIGEgaGlnaGVyIGluZGV4IG51bWJlci4nLCB7IG5zOiBJMThOX05BTUVTUEFDRSB9KX08L2xpPlxuICAgICAgICAgICAgPGxpPnt0KCdJZiB5b3UgY2Fubm90IHNlZSB5b3VyIG1vZCBpbiB0aGlzIGxvYWQgb3JkZXIsIHlvdSBtYXkgbmVlZCB0byBhZGQgaXQgbWFudWFsbHkgKHNlZSBvdXIgd2lraSBmb3IgZGV0YWlscykuJywgeyBuczogSTE4Tl9OQU1FU1BBQ0UgfSl9PC9saT5cbiAgICAgICAgICAgIDxsaT57dCgnV2hlbiBtYW5hZ2luZyBtZW51IG1vZHMsIG1vZCBzZXR0aW5ncyBjaGFuZ2VkIGluc2lkZSB0aGUgZ2FtZSB3aWxsIGJlIGRldGVjdGVkIGJ5IFZvcnRleCBhcyBleHRlcm5hbCBjaGFuZ2VzIC0gdGhhdCBpcyBleHBlY3RlZCwgJ1xuICAgICAgICAgICAgICArICdjaG9vc2UgdG8gdXNlIHRoZSBuZXdlciBmaWxlIGFuZCB5b3VyIHNldHRpbmdzIHdpbGwgYmUgbWFkZSBwZXJzaXN0ZW50LicsXG4gICAgICAgICAgICAgIHsgbnM6IEkxOE5fTkFNRVNQQUNFIH0pfTwvbGk+XG4gICAgICAgICAgICA8bGk+e3QoJ01lcmdlcyBnZW5lcmF0ZWQgYnkgdGhlIFdpdGNoZXIgMyBTY3JpcHQgbWVyZ2VyIG11c3QgYmUgbG9hZGVkIGZpcnN0IGFuZCBhcmUgbG9ja2VkIGluIHRoZSBmaXJzdCBsb2FkIG9yZGVyIHNsb3QuJywgeyBuczogSTE4Tl9OQU1FU1BBQ0UgfSl9PC9saT5cbiAgICAgICAgICA8L3VsPlxuICAgICAgICAgIDxCUy5CdXR0b25cbiAgICAgICAgICAgIG9uQ2xpY2s9eygpID0+IHRvZ2dsZU1vZHNTdGF0ZShmYWxzZSl9XG4gICAgICAgICAgICBzdHlsZT17eyBtYXJnaW5Cb3R0b206ICc1cHgnLCB3aWR0aDogJ21pbi1jb250ZW50JyB9fVxuICAgICAgICAgID5cbiAgICAgICAgICAgIHt0KCdEaXNhYmxlIEFsbCcpfVxuICAgICAgICAgIDwvQlMuQnV0dG9uPlxuICAgICAgICAgIDxiciAvPlxuICAgICAgICAgIDxCUy5CdXR0b25cbiAgICAgICAgICAgIG9uQ2xpY2s9eygpID0+IHRvZ2dsZU1vZHNTdGF0ZSh0cnVlKX1cbiAgICAgICAgICAgIHN0eWxlPXt7IG1hcmdpbkJvdHRvbTogJzVweCcsIHdpZHRoOiAnbWluLWNvbnRlbnQnIH19XG4gICAgICAgICAgPlxuICAgICAgICAgICAge3QoJ0VuYWJsZSBBbGwgJyl9XG4gICAgICAgICAgPC9CUy5CdXR0b24+XG4gICAgICAgIDwvZGl2PlxuICAgICAgPC9kaXY+XG4gICk7XG59XG4iXX0=